### ISSUE TITLE
Plugin does not work on Sketch 52,6  Build(67491)

### ISSUE THREAD

**Issue by OsSi3** [griffin-stewie/SymbolNameAutocomplete#1]
Hi, the plugin does not work for me. I restarted sketch, but still not working.

Does anyone has the same issue?

Sketch version: **Sketch 52,6**  
Build: **67491**

**Comment by griffin-stewie** [comment]
Hi, @OsSi3 

Thank you for using my first published Sketch plugin.

I'm using same Sketch.app version and works fine. I would like to ask some questions.

- Which version of macOS are you using?
- Does your sketch file already has local symbols?

**Comment by OsSi3** [comment]
> Hi, @OsSi3
> 
> Thank you for using my first published Sketch plugin.
> 
> I'm using same Sketch.app version and works fine. I would like to ask some questions.
> 
> * Which version of macOS are you using?
> * Does your sketch file already has local symbols?

macOs Mojave
Version 10.14.2

Yes, my sketch file already had symbols

Edit: I tried on a new sketch file with 0 symbols. It still didnt work for me.

**Comment by griffin-stewie** [comment]
I'm using Mojave 10.14.2 as well.

I have no idea why my plugin doesn't work on your environment now.

-----

> Edit: I tried on a new sketch file with 0 symbols. It still didnt work for me.

"didn't work" is expectation result on this situation. This plugin can help you if you already had `local` symbols because plugin can understands naming rule on your sketch file.

**Comment by griffin-stewie** [comment]
I just added a video how my plugin works [here](https://vimeo.com/312116509). This video  may transcoding by Vimeo at this moment but you'll see when its done.

**Comment by OsSi3** [comment]
> I just added a video how my plugin works [here](https://vimeo.com/312116509). This video may transcoding by Vimeo at this moment but you'll see when its done.

Hi, i have been using Sketch for years now. I know how the plugins work. I just dont get yours to work. Really strange. Maybe i have to restart my pc sometime to test that.

**Comment by griffin-stewie** [comment]
Hummm, I don't know why my plugin doesn't work even if I'm a author. Sorry about that.
