### ISSUE TITLE
Can't override autocomplete

### ISSUE THREAD

**Issue by iamhenry** [griffin-stewie/SymbolNameAutocomplete#2]
This is a really cool plugin that I was excited to use but when I tried to create a new symbol by giving it the name "Profile" it didn't allow me to override "progress". I'm trying to name the new symbol sentence case but I'm unable to. 

Is there a way around this?

![image](https://user-images.githubusercontent.com/923439/54841352-60856c80-4c8c-11e9-860e-11ddbc2a2ab5.png)

**Comment by griffin-stewie** [comment]
@iamhenry First of all, Thank you for using my plugin.

There is no way to name different starting with same character now. It's a bug.

I'm gonna try to fix it.

**Comment by griffin-stewie** [comment]
@iamhenry 
I fixed it.  [Try this plugin](https://github.com/griffin-stewie/SymbolNameAutocomplete/releases/latest) .
